<?php
/*
 * Homework  8
 * Jeff Pollack
 * Time logged on assignemt: hours 12
 */
if (isset($_POST['cases'])) {
    $cases = $_POST['cases'];
} else {
    $cases = '';
}

if (isset($_POST['packs'])) {
    $packs = $_POST['packs'];
} else {
    $packs = '';
}

if (isset($_POST['cardsInPack'])) {
    $cardsInPack = $_POST['cardsInPack'];
} else {
    $cardsInPack = '';
}

if (isset($_POST['uncommon'])) {
    $uncommon = $_POST['uncommon'];
} else {
    $uncommon = '';
}

if (isset($_POST['rare'])) {
    $rare = $_POST['rare'];
} else {
    $rare = '';
}

if (isset($_POST['legendary'])) {
    $legendary = $_POST['legendary'];
} else {
    $legendary = '';
}
?>

<form method="post" action="index.php">
    <label>Total Number of Cases:</label>
    <input type='text' name='cases' size='5' maxlength='5' value='<?= $cases ?>'/><br/>
    <label>Number of Packs in each Case:</label>
    <input type='text' name='packs' size='5' maxlength='5' value='<?= $packs ?>'/><br/>
    <label>Base Number of Cards in each Pack:</label>
    <input type='text' name='cardsInPack' size='5' maxlength='5' value='<?= $cardsInPack ?>'/><br/>
    <label>Frequency of “Uncommon” cards:</label>
    <input type='text' name='uncommon' size='5' maxlength='5' value='<?= $uncommon ?>'/><br/>
    <label>Frequency of “Rare” cards:</label>
    <input type='text' name='rare' size='5' maxlength='5' value='<?= $rare ?>'/><br/>
    <label>Frequency of “Legendary” cards:</label>
    <input type='text' name='legendary' size='5' maxlength='5' value='<?= $legendary ?>'/><br/>
    <input type='submit' name='Filter' value="Process the Case"/>
</form>

<?php
// Generates a number
class Card {
    private $num;
    // make number
    public function __construct($num) {
        $this->num = $num;
    }
    // returns as a string
    public function __toString() {
        return $this->num . ' ';
    }
    // Access the visitor class to process number
    public function cardMaker(Visitor $v) {
        $result = $v->increment();
        if ($result) {
            $this->num = $result;
        }
    }
}
// Process the number that had been generated by the Card class
class Visitor {
    // imputs
    public $cardCount;
    public $uncommon = 0;
    public $rare = 0;
    public $legendary = 0;
    // card counts
    public $COMcount = 0;
    public $UNCcount = 0;
    public $RARcount = 0;
    public $LEGcount = 0;
    // card points
    public $COMpoint = 0;
    public $UNCpoint = 0;
    public $RARpoint = 0;
    public $LEGpoint = 0;
    // Takes the imputs from user
    public function __construct($uncommon, $rare, $legendary, $cardCount) {
        $this->legendary = $legendary;
        $this->uncommon = $uncommon;
        $this->rare = $rare;
        $this->cardCount = $cardCount;
    }
    // Assigns a value, points and count to the card
    public function increment() {
        $out = '';
        if($this->cardCount>0){
            if (($this->cardCount % $this->legendary == 0) ||
                    ($this->cardCount % $this->uncommon == 0 && $this->cardCount % $this->rare == 0) ||
                    ($this->cardCount % $this->rare == 0 && $this->cardCount % $this->legendary == 0) ||
                    ($this->cardCount % $this->uncommon == 0 && $this->cardCount % $this->legendary == 0)) {
                $this->LEGcount++;
                $this->LEGpoint+=12;
                $out.="LEG ";
            } elseif ($this->cardCount % $this->rare == 0) {
                $this->RARcount++;
                $this->RARpoint+=7;
                $out.="RAR ";
            } elseif ($this->cardCount % $this->uncommon == 0) {
                $this->UNCcount++;
                $this->UNCpoint+=3;
                $out.="UNC ";
            } elseif (($this->cardCount % $this->uncommon !== 0) &&
                    ($this->cardCount % $this->rare !== 0) &&
                    ($this->cardCount % $this->legendary !== 0)) {
                $this->COMcount++;
                $this->COMpoint+=1;
                $out.="COM ";
            }
            $this->cardCount--;
        }
        return $out;
    }
}
// Total count of all the cards based on the user imput
$cardCount = ($cardsInPack * $packs) * $cases;
$arr = array();
// Make a Visitor() based on the user imput
$c = new Visitor($uncommon, $rare, $legendary, $cardCount);
// Make a Card() for every card
for ($i=1; $i<=$cardCount; $i++) {
    $arr[] = new Card($i);
}

foreach ($arr as $val) {
    $val->cardMaker($c);
}
// Place holder variables to use as counters in following loop
$cp = 0;//the cards in pack
$p = 1;//the packs
$z = 1;//the cases
$totalPoints=$c->COMpoint+$c->LEGpoint+$c->RARpoint+$c->UNCpoint;
if($packs!=0||$cases!=0){$averagePoints=($totalPoints)/($packs*$cases);}

while ($z <= $cases) {// Echo out each case
    while ($p <= $packs) {// Echo out each pack in the case
        $comCard=0;
        $COMpoint=0;
        $UNCpoint=0;
        $RARpoint=0;
        $LEGpoint=0;
        for ($i=0; $i < $cardsInPack; $i++) {// Echo out each card in a pack
            echo $arr[$cp];
            if (($cp % $c->legendary == 0)||($cp % $c->uncommon == 0 && $cp % $c->rare == 0)||($cp % $c->rare == 0 && $cp % $c->legendary == 0)||($cp % $c->uncommon == 0 && $cp % $c->legendary == 0)){
                $LEGpoint+=12;
            }elseif($cp % $c->rare == 0) {
                $RARpoint+=7;
            }elseif($cp % $c->uncommon == 0) {
                $UNCpoint+=3;
            }elseif(($cp % $c->uncommon !== 0)&&($cp % $c->rare !== 0)||($cp % $c->legendary !== 0)){
                $comCard++;//adds one for each COM card
                $COMpoint+=1;
            }
            $cp++;// Incrementing though the cards
            if($comCard==$cardsInPack){//checks if the number of COM cards in the pack is equal to the standard number of cards in the deck
                echo "COM ";
            }
        }
        $deckPoints=$LEGpoint+$COMpoint+$RARpoint+$UNCpoint;
        if($deckPoints<$averagePoints){
            echo"COM ";
        }        
        $p++;// Incrementing though the packs
        echo"<br/>";
    }
    $p = 1;
    $z++;// Incrementing though the cases
    echo"End of case<br><br/>";
}

if($arr){
echo "<br>There are: <br/>"
.$c->COMcount." common cards.<br/>"
.$c->UNCcount." uncommon cards.<br/>"
.$c->RARcount." rare cards.<br/>"
.$c->LEGcount." legendary cards.<br/>";

echo "<br>The average points per pack are ". number_format($averagePoints,2);}